### ISSUE TITLE
bug in dbGetInfo method

### ISSUE THREAD

**Issue by mdsumner** [teramonagi/RODBCDBI#8]
I believe this method should be more something like this: 

``` R

setMethod("dbGetInfo", "ODBCConnection",
          function (dbObj, ...) {
    info <- RODBC::odbcGetInfo(dbObj@odbc)
    list(host = info["DBMS_Name"], serverVersion = info["DBMS_Ver"], user = "", host = "", port = "",       dbname = info["Data_Source_Name"])
 }
)

```

Currently it's trying to do dbObj(dbObj, ...) which doesn't make sense. I haven't worked through other aspects related to the return object, but this is working for me for dplyr now. Thanks

**Comment by teramonagi** [comment]
OK, i will fix it quickly based on your code.

> but this is working for me for dplyr now. Thanks

Oh I want to know this!
Could you show me an example?

**Comment by mdsumner** [comment]
Sorry, that was premature!  It's kind of working, I had some issues and not sure if they are problems with RODBCDBI or something I'm doing. I got all the way through the "Adding a SQL back-end" vignette until the tbl(x, "tablename") - still have to figure out some more. I send what I have soon

**Comment by teramonagi** [comment]
What you are trying to do is one of the things which I really wana do... Keep up the good work!

**Comment by teramonagi** [comment]
Fixed! You can install the fixed package by the following command.

> devtools::install_github("teramonagi/RODBCDBI")

Thanks alot.
